---
main:
  jellyfin_url: http://jellyfin.jealwh.local
  jellyfin_user: white

collections:
  # Episodes that haven't been watched yet
  TV Shows - Unplayed:
    query: WHERE Played = false
    from: TV Shows

  # Episodes that have been watched ("re-runs")
  TV Shows - Played:
    query: WHERE Played = true
    from: TV Shows

  # Unwatched Taskmaster (UK, NZ, AU, ...) episodes
  Taskmaster - Unplayed:
    query: WHERE Played = false AND SeriesName LIKE "Taskmaster"
    from: TV Shows

  # Simpsons episodes of the 1990s
  Simpsons - 90s Episodes:
    query: WHERE SeriesName LIKE "Simpsons" AND ProductionYear > 1989 AND ProductionYear < 2000
    from: TV Shows

  # Movies that haven't been watched yet
  Movies - Unplayed, newer than 1940:
    query: WHERE Played = false AND ProductionYear > 1940
    from: Movies

  # Old movies that haven't been watched yet
  Movies - Unplayed, older than 1940:
    query: WHERE Played = false AND ProductionYear < 1940
    from: Movies
