---
name: YAML Lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main"]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '.github/workflows/yaml-lint.yaml'

permissions:
  contents: read
  packages: read
  statuses: write
  checks: write

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yamllint
          pip install -r requirements.txt

      - name: Run YAML Lint
        run: yamllint .
